language: python
python:
  - "3.5"
env:
  - DJANGO_SETTINGS_MODULE=ofm_helper.settings.test
install:
  - pip install -r requirements.txt
  - pip install -r travis_requirements.txt
  - pip install coveralls
  - mkdir database
script:
  - ./manage.py migrate
  - coverage run --branch --source . manage.py test

notifications:
  email:
    recipients:
      - witmic1@gmail.com
      - stegschreck@gmail.com
    on_success: change
    on_failure: always

after_success: coveralls
