language: python
python:
  - "3.5"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install xvfb
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - ./manage.py migrate
  - coverage run --branch --source . manage.py test

notifications:
  email:
    recipients:
      - witmic1@gmail.com
      - stegschreck@gmail.com
    on_success: change
    on_failure: always

after_success: coveralls
