version: "2"

services:
  web:
    image: wischlabs/ofm_helper
    volumes:
      - /usr/src/app
      - /usr/src/app/staticfiles
    restart: unless-stopped

  nginx:
    image: wischlabs/ofm_nginx
    ports:
      - "80:80"
    volumes_from:
      - web
    restart: unless-stopped

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    restart: unless-stopped

  #redis:
  #  restart: always
  #  image: redis
  #  ports:
  #    - "6379:6379"
  #  volumes:
  #    - redisdata:/data

  phantomjs:
    image: wernight/phantomjs
    entrypoint: phantomjs
    command: "--webdriver=8910"
    restart: unless-stopped

volumes:
  pgdata:
  #redisdata: