web:
  build: .
  volumes:
    - /usr/src/app
    - /usr/src/app/staticfiles
  links:
    - db
    - phantomjs
  #  - memcached
  ports:
    - "8000:8000"

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

db:
  restart: always
  image: postgres
  ports:
    - "5432:5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/

#redis:
#  restart: always
#  image: redis
#  ports:
#    - "6379:6379"
#  volumes:
#    - redisdata:/data

phantomjs:
    image: wernight/phantomjs
    entrypoint: phantomjs
    command: "--webdriver=8910"